### ISSUE TITLE
Detect whether the build is as a crate or the toplevel?

### ISSUE THREAD

**Issue by Ekleog** [davidpdrsn/todo-or-die#7]
Thinking about where I'd like to use this crate, I figured out that I'd love to be using it in crates that I'm also uploading on crates.io. However, this would mean that the crate uploaded to crates.io would stop compiling after some time, which is Bad(tm). So I'm wondering, do you think there's a chance to detect whether the crate is being built directly or as a crates.io dependency, and (dis)able the warnings depending on that?

My guess would be it's not reasonably doable, but maybe I'm wrong and there's a solution? Besides that, the only other idea I can think of would be to have a feature to enable the todo-or-die, but then one'd have to remember to build with that feature from time to time to check new todos haven't triggered.

What do you think about this?

**Comment by davidpdrsn** [comment]
Publishing things to crates.io that uses todo-or-die doesn't sound like a good idea no matter what 😅

But I'm not actually sure this is possible 🤔

**Comment by trevyn** [comment]
I do this, and run tests in CI:

```toml
[dev-dependencies]
todo-or-die = {version = "0.1", features = ["github"]}
```
```rust
#[cfg(test)]
todo_or_die::issue_closed!("rust-lang", "rust", 54725); // span.join()
```
Works great!
