### ISSUE TITLE
Activatable todos

### ISSUE THREAD

**Issue by makaleks** [davidpdrsn/todo-or-die#8]
While prototyping (sometimes for a long)), I often bypass universality in multiple places, so spawn todos. But currently, for this case, I can't use this crate: I can't make time predictions for my pet-project to use `after_date! `, and can't use the rest as I'm still prototyping, so can't integrate Github. So I need some activatable todo, maybe when building release or via some environment variable. To choose time and instead of grepping for todos get compilation errors. May I be not alone?

Thanks

**Comment by davidpdrsn** [comment]
There is an [environmental variable to skip checks](https://docs.rs/todo-or-die/0.1.2/todo_or_die/#skipping-checks). Would this work for you?

**Comment by makaleks** [comment]
Missed that section, sorry. Now I can use recently-stabilized config.toml with [env] section to disable all todos. There may be a problem with a broken compatibility with other kinds of todos, but I can't formulate why new kind of todo is inevitable yet. I'll close this, thanks
